version: "3.2"
services:
  room-service:
    build:
      context: ${ROOM_DIRECTORY}
      dockerfile: ../docker/room-service/Dockerfile
    environment:
      - PORT=${ROOM_SERVICE_PORT}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./room-service:/usr/src/app/
    networks:
      - app-network

  auth-service:
    build:
      context: ${AUTH_DIRECTORY}
      dockerfile: ../docker/auth-service/Dockerfile
    command: npx nodemon src/index.ts
    container_name: 'auth-service'
    environment:
      - PORT=${AUTH_SERVICE_PORT}
    volumes:
      - ./auth-service:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - room-service
      - auth-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
