version: "3.2"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    command: npm start
    stdin_open: true
    tty: true
    container_name: ${PROJECT_NAME}-frontend
    volumes:
      - ${FRONTEND_DIRECTORY}:/var/www/project/frontend
      - /var/www/project/frontend/node_modules
    networks:
      - ${PROJECT_NAME}

  room-service:
    build:
      context: ${ROOM_DIRECTORY}
      dockerfile: ../docker/room-service/Dockerfile
    environment:
      - PORT=${ROOM_SERVICE_PORT}
      - NODE_ENV=${NODE_ENV}
    container_name: ${PROJECT_NAME}-room-service
    volumes:
      - ./room-service:/usr/src/app/
    networks:
      - ${PROJECT_NAME}

  auth-service:
    build:
      context: ${AUTH_DIRECTORY}
      dockerfile: ../docker/auth-service/Dockerfile
    command: npx nodemon src/index.ts
    container_name: ${PROJECT_NAME}-auth-service
    environment:
      - PORT=${AUTH_SERVICE_PORT}
    volumes:
      - ./auth-service:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - ${PROJECT_NAME}

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: unless-stopped
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - ${PROJECT_NAME}

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${FRONTEND_DIRECTORY}:/var/www/project/frontend
      - ./docker/certs/local/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    depends_on:
      - room-service
      - auth-service
      - frontend
    networks:
      - ${PROJECT_NAME}

networks:
  project:

volumes:
  mysql:
