version: "3.2"
services:
  nestjs_api:
    build:
      dockerfile: ./docker/room-service/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./room-service:/usr/src/app/

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
