export enum Events {
  setUserData = 'user:setUserData',
  startGameWithBot = 'user:startGameWithBot',
  createRoom = 'user:createRoom',
  handleMove = 'room:handleMove',
  joinRoom = 'room:joinRoom',
  deleteRoom = 'room:delete',
  handleOfferDraw = 'room:handleOfferDraw',
  acceptDraw = 'room:acceptDraw',
  denyDraw = 'room:denyDraw',
  leaveRoom = 'room:leaveRoom',
  getTime = 'room:getTime',
  timeRunOut = 'room:timeRunOut',
  startGame = 'user:startGame',
  stopGameFind = 'user:stopGameFind',
  surrender = 'room:surrender',
}