http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  auth:
    host: localhost
    paths: '/auth'
serviceEndpoints:
  httpbin:
    url: 'https://chessworld.ua'
  roomService:
    url: 'http://nestjs_api:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  auth-pipeline:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: roomService
              changeOrigin: true
